-- ============================================================
-- RAW Layer DDL - NovaStar Brands Corp
-- Dataset: Src_NovaStar
-- ============================================================

-- Create dataset
CREATE SCHEMA IF NOT EXISTS Src_NovaStar
OPTIONS (location = 'us-central1');

-- ─── Company Master ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_company (
  COMPANY_CODE STRING NOT NULL,
  COMPANY_NAME STRING,
  REGION STRING,
  CURRENCY_CODE STRING,
  GEOGRAPHIC_SECURITY_CODE STRING,
  COUNTRY STRING,
  STATUS STRING,
  LOAD_DATE TIMESTAMP
);

-- ─── Customer Master ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_customer (
  CUSTOMER_CODE STRING NOT NULL,
  CUSTOMER_NAME STRING,
  CUSTOMER_TYPE STRING,
  STATUS STRING,
  CREDIT_LIMIT INT64,
  PAYMENT_TERMS STRING,
  LOAD_DATE TIMESTAMP
);

-- ─── Product Master ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_product (
  TOY_NO STRING NOT NULL,
  DASH_CODE STRING NOT NULL,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  BRAND STRING,
  STATUS STRING,
  LAUNCH_DATE DATE,
  WEIGHT_KG NUMERIC,
  LOAD_DATE TIMESTAMP
);

-- ─── Product Prices ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_price (
  TOY_NO STRING NOT NULL,
  DASH_CODE STRING NOT NULL,
  PRICE_TYPE STRING NOT NULL,
  PRICE NUMERIC,
  CURRENCY_CODE STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  LOAD_DATE TIMESTAMP
);

-- ─── Product Costs ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_cost (
  TOY_NO STRING NOT NULL,
  DASH_CODE STRING NOT NULL,
  COST_TYPE STRING NOT NULL,
  COST NUMERIC,
  CURRENCY_CODE STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  LOAD_DATE TIMESTAMP
);

-- ─── Order Lines (Sales Transactions) ──────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_order_line (
  ORDER_ID STRING NOT NULL,
  ORDER_LINE_NO INT64 NOT NULL,
  TRANSACTION_DATE DATE,
  COMPANY_CODE STRING,
  SELLING_METHOD_CODE STRING,
  CUSTOMER_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  ORDER_STATUS STRING,
  ORDER_TYPE STRING,
  ORDER_QTY INT64,
  LIST_PRICE NUMERIC,
  SELLING_PRICE NUMERIC,
  DISCOUNT_PCT INT64,
  ORDER_VALUE NUMERIC,
  ORDER_LIST_VALUE NUMERIC,
  CURRENCY_CODE STRING,
  LOAD_DATE TIMESTAMP
);

-- ─── Returns ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_return (
  RETURN_ID STRING NOT NULL,
  ORDER_ID STRING,
  ORDER_LINE_NO INT64,
  RETURN_DATE DATE,
  COMPANY_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  RETURN_QTY INT64,
  RETURN_VALUE NUMERIC,
  RETURN_REASON STRING,
  CURRENCY_CODE STRING,
  LOAD_DATE TIMESTAMP
);

-- ─── Demand Forecasts ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_demand_forecast (
  FORECAST_ID STRING NOT NULL,
  AS_OF_DATE DATE,
  FORECAST_DATE DATE,
  COMPANY_CODE STRING,
  SELLING_METHOD_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  DEMAND_PLAN_QTY INT64,
  DEMAND_PLAN_DRAFT_QTY INT64,
  LINE_OF_BUSINESS_CODE STRING,
  CURRENCY_CODE STRING,
  LOAD_DATE TIMESTAMP
);

-- ─── Sales Forecasts ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS Src_NovaStar.raw_sales_forecast (
  FORECAST_ID STRING NOT NULL,
  AS_OF_DATE DATE,
  FORECAST_DATE DATE,
  COMPANY_CODE STRING,
  SELLING_METHOD_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  SALES_FORECAST_QTY INT64,
  SALES_FORECAST_STAGED_QTY INT64,
  CURRENCY_CODE STRING,
  LOAD_DATE TIMESTAMP
);
