-- ============================================================
-- CDL Layer DDL - NovaStar Brands Corp
-- Cleansed Data Layer: conformed dimensions + facts
-- Dataset: CDL_NovaStar
-- ============================================================

CREATE SCHEMA IF NOT EXISTS CDL_NovaStar
OPTIONS (location = 'us-central1');

-- ─── Dimension: Company ────────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_dim_company (
  KEY_COMPANY INT64 NOT NULL,
  COMPANY_CODE STRING,
  COMPANY_NAME STRING,
  REGION STRING,
  CURRENCY_CODE STRING,
  GEOGRAPHIC_SECURITY_CODE STRING,
  COUNTRY STRING,
  STATUS STRING,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Dimension: Customer ───────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_dim_customer (
  KEY_CUSTOMER INT64 NOT NULL,
  CUSTOMER_CODE STRING,
  CUSTOMER_NAME STRING,
  CUSTOMER_TYPE STRING,
  STATUS STRING,
  CREDIT_LIMIT INT64,
  PAYMENT_TERMS STRING,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Dimension: Product ────────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_dim_product (
  KEY_PRODUCT INT64 NOT NULL,
  TOY_NO STRING,
  DASH_CODE STRING,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  BRAND STRING,
  STATUS STRING,
  LAUNCH_DATE DATE,
  WEIGHT_KG NUMERIC,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Dimension: Selling Method ─────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_dim_selling_method (
  KEY_SELLING_METHOD INT64 NOT NULL,
  SELLING_METHOD_CODE STRING,
  SELLING_METHOD_NAME STRING,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Dimension: Calendar ───────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_dim_calendar (
  KEY_CALENDAR INT64 NOT NULL,
  CALENDAR_DATE DATE,
  YEAR INT64,
  MONTH INT64,
  QUARTER INT64,
  WEEK_OF_YEAR INT64,
  DAY_OF_WEEK INT64,
  IS_WEEKEND BOOLEAN,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Fact: Sales (Invoiced Orders) ─────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_fact_sales (
  KEY_PRODUCT INT64,
  KEY_COMPANY INT64,
  KEY_CUSTOMER INT64,
  KEY_SELLING_METHOD INT64,
  KEY_CALENDAR INT64,
  ORDER_ID STRING,
  ORDER_LINE_NO INT64,
  TRANSACTION_DATE DATE,
  COMPANY_CODE STRING,
  SELLING_METHOD_CODE STRING,
  CUSTOMER_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  ORDER_STATUS STRING,
  ORDER_TYPE STRING,
  ORDER_QTY INT64,
  LIST_PRICE NUMERIC,
  SELLING_PRICE NUMERIC,
  DISCOUNT_PCT INT64,
  ORDER_VALUE NUMERIC,
  ORDER_LIST_VALUE NUMERIC,
  CURRENCY_CODE STRING,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Fact: Returns ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_fact_returns (
  KEY_PRODUCT INT64,
  KEY_COMPANY INT64,
  KEY_CALENDAR INT64,
  RETURN_ID STRING,
  ORDER_ID STRING,
  ORDER_LINE_NO INT64,
  RETURN_DATE DATE,
  COMPANY_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  RETURN_QTY INT64,
  RETURN_VALUE NUMERIC,
  RETURN_REASON STRING,
  CURRENCY_CODE STRING,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Fact: Product Price ───────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_fact_product_price (
  KEY_PRODUCT INT64,
  TOY_NO STRING,
  DASH_CODE STRING,
  PRICE_TYPE STRING,
  PRICE NUMERIC,
  CURRENCY_CODE STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Fact: Product Cost ────────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_fact_product_cost (
  KEY_PRODUCT INT64,
  TOY_NO STRING,
  DASH_CODE STRING,
  COST_TYPE STRING,
  COST NUMERIC,
  CURRENCY_CODE STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Fact: Demand Forecast ─────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_fact_demand_forecast (
  KEY_PRODUCT INT64,
  KEY_COMPANY INT64,
  KEY_SELLING_METHOD INT64,
  FORECAST_ID STRING,
  AS_OF_DATE DATE,
  FORECAST_DATE DATE,
  COMPANY_CODE STRING,
  SELLING_METHOD_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  DEMAND_PLAN_QTY INT64,
  DEMAND_PLAN_DRAFT_QTY INT64,
  LINE_OF_BUSINESS_CODE STRING,
  CURRENCY_CODE STRING,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ─── Fact: Sales Forecast ──────────────────────────────────
CREATE TABLE IF NOT EXISTS CDL_NovaStar.cdl_fact_sales_forecast (
  KEY_PRODUCT INT64,
  KEY_COMPANY INT64,
  KEY_SELLING_METHOD INT64,
  FORECAST_ID STRING,
  AS_OF_DATE DATE,
  FORECAST_DATE DATE,
  COMPANY_CODE STRING,
  SELLING_METHOD_CODE STRING,
  TOY_NO STRING,
  DASH_CODE STRING,
  SALES_FORECAST_QTY INT64,
  SALES_FORECAST_STAGED_QTY INT64,
  CURRENCY_CODE STRING,
  RAW_LOAD_DATE TIMESTAMP,
  CDL_LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
