-- ============================================================
-- RAW → CDL Transformation SQL - NovaStar Brands Corp
-- Populates CDL conformed dimensions and facts from RAW
-- ============================================================

-- ─── CDL Dimension: Company ────────────────────────────────
MERGE INTO CDL_NovaStar.cdl_dim_company T
USING (
  SELECT
    FARM_FINGERPRINT(COMPANY_CODE) AS KEY_COMPANY,
    COMPANY_CODE,
    COMPANY_NAME,
    REGION,
    CURRENCY_CODE,
    GEOGRAPHIC_SECURITY_CODE,
    COUNTRY,
    STATUS,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_company
) S
ON T.KEY_COMPANY = S.KEY_COMPANY
WHEN MATCHED THEN UPDATE SET
  T.COMPANY_NAME = S.COMPANY_NAME,
  T.REGION = S.REGION,
  T.CURRENCY_CODE = S.CURRENCY_CODE,
  T.GEOGRAPHIC_SECURITY_CODE = S.GEOGRAPHIC_SECURITY_CODE,
  T.COUNTRY = S.COUNTRY,
  T.STATUS = S.STATUS,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_COMPANY, COMPANY_CODE, COMPANY_NAME, REGION, CURRENCY_CODE,
  GEOGRAPHIC_SECURITY_CODE, COUNTRY, STATUS, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_COMPANY, S.COMPANY_CODE, S.COMPANY_NAME, S.REGION, S.CURRENCY_CODE,
  S.GEOGRAPHIC_SECURITY_CODE, S.COUNTRY, S.STATUS, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Dimension: Customer ───────────────────────────────
MERGE INTO CDL_NovaStar.cdl_dim_customer T
USING (
  SELECT
    FARM_FINGERPRINT(CUSTOMER_CODE) AS KEY_CUSTOMER,
    CUSTOMER_CODE,
    CUSTOMER_NAME,
    CUSTOMER_TYPE,
    STATUS,
    CREDIT_LIMIT,
    PAYMENT_TERMS,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_customer
) S
ON T.KEY_CUSTOMER = S.KEY_CUSTOMER
WHEN MATCHED THEN UPDATE SET
  T.CUSTOMER_NAME = S.CUSTOMER_NAME,
  T.CUSTOMER_TYPE = S.CUSTOMER_TYPE,
  T.STATUS = S.STATUS,
  T.CREDIT_LIMIT = S.CREDIT_LIMIT,
  T.PAYMENT_TERMS = S.PAYMENT_TERMS,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_CUSTOMER, CUSTOMER_CODE, CUSTOMER_NAME, CUSTOMER_TYPE,
  STATUS, CREDIT_LIMIT, PAYMENT_TERMS, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_CUSTOMER, S.CUSTOMER_CODE, S.CUSTOMER_NAME, S.CUSTOMER_TYPE,
  S.STATUS, S.CREDIT_LIMIT, S.PAYMENT_TERMS, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Dimension: Product ────────────────────────────────
MERGE INTO CDL_NovaStar.cdl_dim_product T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    TOY_NO,
    DASH_CODE,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    STATUS,
    LAUNCH_DATE,
    WEIGHT_KG,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_product
) S
ON T.KEY_PRODUCT = S.KEY_PRODUCT
WHEN MATCHED THEN UPDATE SET
  T.PRODUCT_NAME = S.PRODUCT_NAME,
  T.CATEGORY = S.CATEGORY,
  T.BRAND = S.BRAND,
  T.STATUS = S.STATUS,
  T.LAUNCH_DATE = S.LAUNCH_DATE,
  T.WEIGHT_KG = S.WEIGHT_KG,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, TOY_NO, DASH_CODE, PRODUCT_NAME, CATEGORY,
  BRAND, STATUS, LAUNCH_DATE, WEIGHT_KG, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.TOY_NO, S.DASH_CODE, S.PRODUCT_NAME, S.CATEGORY,
  S.BRAND, S.STATUS, S.LAUNCH_DATE, S.WEIGHT_KG, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Dimension: Selling Method ─────────────────────────
MERGE INTO CDL_NovaStar.cdl_dim_selling_method T
USING (
  SELECT
    FARM_FINGERPRINT(code) AS KEY_SELLING_METHOD,
    code AS SELLING_METHOD_CODE,
    name AS SELLING_METHOD_NAME
  FROM UNNEST([
    STRUCT('100' AS code, 'Wholesale' AS name),
    STRUCT('200', 'Direct-to-Consumer'),
    STRUCT('300', 'E-Commerce'),
    STRUCT('400', 'Marketplace')
  ])
) S
ON T.KEY_SELLING_METHOD = S.KEY_SELLING_METHOD
WHEN NOT MATCHED THEN INSERT (
  KEY_SELLING_METHOD, SELLING_METHOD_CODE, SELLING_METHOD_NAME, CDL_LOAD_DATE
) VALUES (
  S.KEY_SELLING_METHOD, S.SELLING_METHOD_CODE, S.SELLING_METHOD_NAME, CURRENT_TIMESTAMP()
);

-- ─── CDL Dimension: Calendar ───────────────────────────────
MERGE INTO CDL_NovaStar.cdl_dim_calendar T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(CAST(EXTRACT(YEAR FROM d) AS STRING), CAST(d AS STRING))) AS KEY_CALENDAR,
    d AS CALENDAR_DATE,
    EXTRACT(YEAR FROM d) AS YEAR,
    EXTRACT(MONTH FROM d) AS MONTH,
    EXTRACT(QUARTER FROM d) AS QUARTER,
    EXTRACT(ISOWEEK FROM d) AS WEEK_OF_YEAR,
    EXTRACT(DAYOFWEEK FROM d) AS DAY_OF_WEEK,
    EXTRACT(DAYOFWEEK FROM d) IN (1, 7) AS IS_WEEKEND
  FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2025-12-31')) AS d
) S
ON T.KEY_CALENDAR = S.KEY_CALENDAR
WHEN NOT MATCHED THEN INSERT (
  KEY_CALENDAR, CALENDAR_DATE, YEAR, MONTH, QUARTER,
  WEEK_OF_YEAR, DAY_OF_WEEK, IS_WEEKEND, CDL_LOAD_DATE
) VALUES (
  S.KEY_CALENDAR, S.CALENDAR_DATE, S.YEAR, S.MONTH, S.QUARTER,
  S.WEEK_OF_YEAR, S.DAY_OF_WEEK, S.IS_WEEKEND, CURRENT_TIMESTAMP()
);

-- ─── CDL Fact: Product Price ───────────────────────────────
MERGE INTO CDL_NovaStar.cdl_fact_product_price T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    TOY_NO,
    DASH_CODE,
    PRICE_TYPE,
    PRICE,
    CURRENCY_CODE,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_price
) S
ON T.KEY_PRODUCT = S.KEY_PRODUCT
  AND T.PRICE_TYPE = S.PRICE_TYPE
  AND T.EFFECTIVE_DATE = S.EFFECTIVE_DATE
WHEN MATCHED THEN UPDATE SET
  T.PRICE = S.PRICE,
  T.CURRENCY_CODE = S.CURRENCY_CODE,
  T.EXPIRY_DATE = S.EXPIRY_DATE,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, TOY_NO, DASH_CODE, PRICE_TYPE, PRICE,
  CURRENCY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.TOY_NO, S.DASH_CODE, S.PRICE_TYPE, S.PRICE,
  S.CURRENCY_CODE, S.EFFECTIVE_DATE, S.EXPIRY_DATE, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Fact: Product Cost ────────────────────────────────
MERGE INTO CDL_NovaStar.cdl_fact_product_cost T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    TOY_NO,
    DASH_CODE,
    COST_TYPE,
    COST,
    CURRENCY_CODE,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_cost
) S
ON T.KEY_PRODUCT = S.KEY_PRODUCT
  AND T.COST_TYPE = S.COST_TYPE
  AND T.EFFECTIVE_DATE = S.EFFECTIVE_DATE
WHEN MATCHED THEN UPDATE SET
  T.COST = S.COST,
  T.CURRENCY_CODE = S.CURRENCY_CODE,
  T.EXPIRY_DATE = S.EXPIRY_DATE,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, TOY_NO, DASH_CODE, COST_TYPE, COST,
  CURRENCY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.TOY_NO, S.DASH_CODE, S.COST_TYPE, S.COST,
  S.CURRENCY_CODE, S.EFFECTIVE_DATE, S.EXPIRY_DATE, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Fact: Sales ───────────────────────────────────────
MERGE INTO CDL_NovaStar.cdl_fact_sales T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    FARM_FINGERPRINT(COMPANY_CODE) AS KEY_COMPANY,
    FARM_FINGERPRINT(CUSTOMER_CODE) AS KEY_CUSTOMER,
    FARM_FINGERPRINT(SELLING_METHOD_CODE) AS KEY_SELLING_METHOD,
    FARM_FINGERPRINT(CONCAT(CAST(EXTRACT(YEAR FROM TRANSACTION_DATE) AS STRING), CAST(TRANSACTION_DATE AS STRING))) AS KEY_CALENDAR,
    ORDER_ID,
    ORDER_LINE_NO,
    TRANSACTION_DATE,
    COMPANY_CODE,
    SELLING_METHOD_CODE,
    CUSTOMER_CODE,
    TOY_NO,
    DASH_CODE,
    ORDER_STATUS,
    ORDER_TYPE,
    ORDER_QTY,
    LIST_PRICE,
    SELLING_PRICE,
    DISCOUNT_PCT,
    ORDER_VALUE,
    ORDER_LIST_VALUE,
    CURRENCY_CODE,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_order_line
) S
ON T.ORDER_ID = S.ORDER_ID AND T.ORDER_LINE_NO = S.ORDER_LINE_NO
WHEN MATCHED THEN UPDATE SET
  T.ORDER_STATUS = S.ORDER_STATUS,
  T.ORDER_QTY = S.ORDER_QTY,
  T.SELLING_PRICE = S.SELLING_PRICE,
  T.ORDER_VALUE = S.ORDER_VALUE,
  T.ORDER_LIST_VALUE = S.ORDER_LIST_VALUE,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, KEY_COMPANY, KEY_CUSTOMER, KEY_SELLING_METHOD, KEY_CALENDAR,
  ORDER_ID, ORDER_LINE_NO, TRANSACTION_DATE, COMPANY_CODE, SELLING_METHOD_CODE,
  CUSTOMER_CODE, TOY_NO, DASH_CODE, ORDER_STATUS, ORDER_TYPE,
  ORDER_QTY, LIST_PRICE, SELLING_PRICE, DISCOUNT_PCT, ORDER_VALUE,
  ORDER_LIST_VALUE, CURRENCY_CODE, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.KEY_COMPANY, S.KEY_CUSTOMER, S.KEY_SELLING_METHOD, S.KEY_CALENDAR,
  S.ORDER_ID, S.ORDER_LINE_NO, S.TRANSACTION_DATE, S.COMPANY_CODE, S.SELLING_METHOD_CODE,
  S.CUSTOMER_CODE, S.TOY_NO, S.DASH_CODE, S.ORDER_STATUS, S.ORDER_TYPE,
  S.ORDER_QTY, S.LIST_PRICE, S.SELLING_PRICE, S.DISCOUNT_PCT, S.ORDER_VALUE,
  S.ORDER_LIST_VALUE, S.CURRENCY_CODE, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Fact: Returns ─────────────────────────────────────
MERGE INTO CDL_NovaStar.cdl_fact_returns T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    FARM_FINGERPRINT(COMPANY_CODE) AS KEY_COMPANY,
    FARM_FINGERPRINT(CONCAT(CAST(EXTRACT(YEAR FROM RETURN_DATE) AS STRING), CAST(RETURN_DATE AS STRING))) AS KEY_CALENDAR,
    RETURN_ID,
    ORDER_ID,
    ORDER_LINE_NO,
    RETURN_DATE,
    COMPANY_CODE,
    TOY_NO,
    DASH_CODE,
    RETURN_QTY,
    RETURN_VALUE,
    RETURN_REASON,
    CURRENCY_CODE,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_return
) S
ON T.RETURN_ID = S.RETURN_ID AND T.ORDER_LINE_NO = S.ORDER_LINE_NO
WHEN MATCHED THEN UPDATE SET
  T.RETURN_QTY = S.RETURN_QTY,
  T.RETURN_VALUE = S.RETURN_VALUE,
  T.RETURN_REASON = S.RETURN_REASON,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, KEY_COMPANY, KEY_CALENDAR, RETURN_ID, ORDER_ID,
  ORDER_LINE_NO, RETURN_DATE, COMPANY_CODE, TOY_NO, DASH_CODE,
  RETURN_QTY, RETURN_VALUE, RETURN_REASON, CURRENCY_CODE, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.KEY_COMPANY, S.KEY_CALENDAR, S.RETURN_ID, S.ORDER_ID,
  S.ORDER_LINE_NO, S.RETURN_DATE, S.COMPANY_CODE, S.TOY_NO, S.DASH_CODE,
  S.RETURN_QTY, S.RETURN_VALUE, S.RETURN_REASON, S.CURRENCY_CODE, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Fact: Demand Forecast ─────────────────────────────
MERGE INTO CDL_NovaStar.cdl_fact_demand_forecast T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    FARM_FINGERPRINT(COMPANY_CODE) AS KEY_COMPANY,
    FARM_FINGERPRINT(SELLING_METHOD_CODE) AS KEY_SELLING_METHOD,
    FORECAST_ID,
    AS_OF_DATE,
    FORECAST_DATE,
    COMPANY_CODE,
    SELLING_METHOD_CODE,
    TOY_NO,
    DASH_CODE,
    DEMAND_PLAN_QTY,
    DEMAND_PLAN_DRAFT_QTY,
    LINE_OF_BUSINESS_CODE,
    CURRENCY_CODE,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_demand_forecast
) S
ON T.FORECAST_ID = S.FORECAST_ID
WHEN MATCHED THEN UPDATE SET
  T.DEMAND_PLAN_QTY = S.DEMAND_PLAN_QTY,
  T.DEMAND_PLAN_DRAFT_QTY = S.DEMAND_PLAN_DRAFT_QTY,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, KEY_COMPANY, KEY_SELLING_METHOD, FORECAST_ID,
  AS_OF_DATE, FORECAST_DATE, COMPANY_CODE, SELLING_METHOD_CODE,
  TOY_NO, DASH_CODE, DEMAND_PLAN_QTY, DEMAND_PLAN_DRAFT_QTY,
  LINE_OF_BUSINESS_CODE, CURRENCY_CODE, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.KEY_COMPANY, S.KEY_SELLING_METHOD, S.FORECAST_ID,
  S.AS_OF_DATE, S.FORECAST_DATE, S.COMPANY_CODE, S.SELLING_METHOD_CODE,
  S.TOY_NO, S.DASH_CODE, S.DEMAND_PLAN_QTY, S.DEMAND_PLAN_DRAFT_QTY,
  S.LINE_OF_BUSINESS_CODE, S.CURRENCY_CODE, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);

-- ─── CDL Fact: Sales Forecast ──────────────────────────────
MERGE INTO CDL_NovaStar.cdl_fact_sales_forecast T
USING (
  SELECT
    FARM_FINGERPRINT(CONCAT(TOY_NO, '-', DASH_CODE)) AS KEY_PRODUCT,
    FARM_FINGERPRINT(COMPANY_CODE) AS KEY_COMPANY,
    FARM_FINGERPRINT(SELLING_METHOD_CODE) AS KEY_SELLING_METHOD,
    FORECAST_ID,
    AS_OF_DATE,
    FORECAST_DATE,
    COMPANY_CODE,
    SELLING_METHOD_CODE,
    TOY_NO,
    DASH_CODE,
    SALES_FORECAST_QTY,
    SALES_FORECAST_STAGED_QTY,
    CURRENCY_CODE,
    LOAD_DATE AS RAW_LOAD_DATE
  FROM Src_NovaStar.raw_sales_forecast
) S
ON T.FORECAST_ID = S.FORECAST_ID
WHEN MATCHED THEN UPDATE SET
  T.SALES_FORECAST_QTY = S.SALES_FORECAST_QTY,
  T.SALES_FORECAST_STAGED_QTY = S.SALES_FORECAST_STAGED_QTY,
  T.RAW_LOAD_DATE = S.RAW_LOAD_DATE,
  T.CDL_LOAD_DATE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  KEY_PRODUCT, KEY_COMPANY, KEY_SELLING_METHOD, FORECAST_ID,
  AS_OF_DATE, FORECAST_DATE, COMPANY_CODE, SELLING_METHOD_CODE,
  TOY_NO, DASH_CODE, SALES_FORECAST_QTY, SALES_FORECAST_STAGED_QTY,
  CURRENCY_CODE, RAW_LOAD_DATE, CDL_LOAD_DATE
) VALUES (
  S.KEY_PRODUCT, S.KEY_COMPANY, S.KEY_SELLING_METHOD, S.FORECAST_ID,
  S.AS_OF_DATE, S.FORECAST_DATE, S.COMPANY_CODE, S.SELLING_METHOD_CODE,
  S.TOY_NO, S.DASH_CODE, S.SALES_FORECAST_QTY, S.SALES_FORECAST_STAGED_QTY,
  S.CURRENCY_CODE, S.RAW_LOAD_DATE, CURRENT_TIMESTAMP()
);
